server:
  port: 8080
spring:
  cloud:
    stream:
      bindings:
        test-messages:
          destination: tst-msg
          group: test-group
          contentType: application/json

logging:
  file: ./logs/ms-trigger.log
  level:
    root: INFO
    ru.alfacapital: DEBUG